version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: streamsphere-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: streamsphere-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/streamsphere
      - PORT=5001
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build: ./frontend
    container_name: streamsphere-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
